version: '3.7'
services:
    # Development watch & compile
    app:
        build: '.'
        volumes:
            - './:/app'
            - '/app/node_modules'
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        ports:
            - '4000:3000'
            - '35729:35729'
